server:
  port: 8081

elide:
  json-api:
    enabled: true
    path: /api
    links:
      enabled: true
  graphql:
    enabled: true
    path: /api/graphql
    subscription:
      enabled: false
      path: /api/subscription
    federation:
      enabled: true
  api-docs:
    enabled: true
    path: /doc
  async:
    enabled: false
    thread-pool-size: 2
    cleanup:
      enabled: true
      query-max-run-time: 65s
      query-retention-duration: 7d
    export:
      enabled: false
  aggregation-store:
    enabled: false
    default-dialect: h2
    metadata-store:
      enabled: false
    dynamic-config:
      enabled: false
      path: analytics
  default-page-size: 2000

spring:
  application:
    name: pharma
  datasource:
    url: 'jdbc:mysql://localhost:3306/pharma?useSSL=false&serverTimezone=Asia/Shanghai'
    username: 'root'
    password: 'root'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    hikari:
      poolName: HikariPool
      minimum-idle: 10
      maximum-pool-size: 60
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQLDialect'
        '[default_batch_fetch_size]': 100
        '[use_scrollable_resultset]': true
        format_sql: true
        order_inserts: true
        order_updates: true
        batch_size: 2000
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy'
    database-platform: org.hibernate.dialect.MySQLDialect
#  jackson:
#    date-format: "yyyy-MM-dd'T'HH:mm:ss"
#    time-zone: GMT+8

logging:
  file:
    path: /tmp
  level:
    root: info
    com.sanofi.onesales.isales: info

#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true  # 自动驼峰转换
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启SQL日志
#  global-config:
#    db-config:
#      logic-delete-field: deleted  # 逻辑删除字段
#      logic-not-delete-value: 0
#      logic-delete-value: 1